name: Recruitment API Automation Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Chạy tự động vào lúc 00:00 (Nửa đêm chuẩn UTC) định kỳ mỗi ngày

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman & HTMLExtra Reporter
        run: |
          npm install -g newman 
          npm install -g newman-reporter-htmlextra

      - name: Start Backend Services (Docker Compose)
        run: |
          docker compose up -d --build
          echo "Waiting for services to initialize..."
          sleep 90 # Đợi Spring Boot khởi động
          docker ps

      - name: Run Postman Collection
        run: |
          newman run recruitment.postman_collection.json \
            -e Local.postman_environment.json \
            -r cli,htmlextra

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: postman-test-report
          path: newman/
